title: Donovan Maree
logo: "/images/me cropped.jpg?raw=true"
description: >

  <br>
  Welcome to my page!
  <br>
  <br>
  <a href="https://www.linkedin.com/in/donovan-maree-90452776/">View My LinkedIn Profile</a> 
  <br>
  <br>
  <a href="https://medium.com/@donovanmaree">View My Articles on Medium</a> 
  <br>
  <br>
  <a href="https://www.producthunt.com/@donovandata">View My Top Product Awards on ProductHunt</a> 
  <br>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0
