title: Donovan Maree
logo: "/images/me cropped.jpg?raw=true"
description: >
  Welcome to my portfolio! As an experienced Data Practitioner with a focus on collaboration between product managers and engineering teams, I've spent over five years building data teams across the globe. My comprehensive experience in the data spectrum, including roles such as Principal Data Scientist and Senior Analytics Engineer, has enabled me to become the nervous system for companies in matters related to data, automation, and AI. I thrive on driving change and improvement across departments with my keen attention to detail and a deep understanding of the balance between delivering results promptly and achieving perfection.

  My passion lies in developing state-of-the-art data infrastructure and guiding talented data teams to achieve their full potential. By fostering collaboration and innovation, I believe we can create data-driven solutions that truly stand out in the global market. My experience informs every new project I undertake, and I'm always eager to tackle new challenges and explore opportunities for growth. Let's connect and unlock the power of data together!

links:
  - title: View My LinkedIn Profile
    url: https://www.linkedin.com/in/donovan-maree-90452776/
  - title: View My Articles on Medium
    url: https://medium.com/@donovanmaree
  - title: View My Top Product Awards on ProductHunt
    url: https://www.producthunt.com/@donovandata

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
