title: Donovan Maree
logo: "/images/me cropped.jpg?raw=true"
description: >
  Welcome to my portfolio!
links:
  - title: View My LinkedIn Profile
    url: https://www.linkedin.com/in/donovan-maree-90452776/
  - title: View My Articles on Medium
    url: https://medium.com/@donovanmaree
  - title: View My Top Product Awards on ProductHunt
    url: https://www.producthunt.com/@donovandata

theme: jekyll-theme-minimal
google_analytics: UA-000000-0
